name: dart_things
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/EsinShadrach/dart-stuff

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  image: ^4.1.7
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
